### ISSUE TITLE
Tracking Issue: 小组页

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/frontend#99]
- [ ] 小组概览 `/group/[name]`
  - [ ] 版头
  - [ ] 小组介绍
  - [ ] 最新讨论
  - [ ] 最近加入
  - [ ] 关联小组
- [ ] 组内讨论 `group/[name]/forum`
  - [ ] 讨论列表
- [ ]  小组成员 `group/[name]/members`
  - [ ] 成员列表 
- [ ] bbcode 解析 https://github.com/bangumi/frontend/pull/100

关联页面
个人页 -> 旧站
讨论详情页 -> 旧站
小组页 -> 新站

设计：https://www.figma.com/file/jW61odhQl5lZzhY4CqvvSF/Web-Page?node-id=0%3A1

**Comment by Trim21** [comment]
可以先按照设计写个api spec出来？

**Comment by Ayase-252** [comment]
前端来写？

**Comment by Trim21** [comment]
> 前端来写？

先搞私有的呗，设计成啥样也只有前端自己用，我感觉问题不大（主要是懒）

**Comment by Ayase-252** [comment]
写哪里呢？（

**Comment by Trim21** [comment]
server仓库？

**Comment by Trim21** [comment]
或者dev-docs

**Comment by Ayase-252** [comment]
到时候开 issue 吧。yaml 我就不写了（

**Comment by Trim21** [comment]
刚想起来有跨仓库的 project 了 https://github.com/orgs/bangumi/projects/3

**Comment by Trim21** [comment]
小组现在有一个ID（uint32）一个name（string），还是跟原来一样在path里面用name作为区分吧。

**Comment by Ayase-252** [comment]
改了

**Comment by Trim21** [comment]
最新讨论的API搞定了。

帖子内容的API还稍微有点问题。（管理员锁定和下沉的操作没有正确返回。）

**Comment by Trim21** [comment]
帖子内容的API也做完了。

这边要开始做的话我就打个新tag，否则也没啥需要更新服务端的…

**Comment by Ayase-252** [comment]
这边有个列表的 API 就行了吧

**Comment by fimars** [comment]
这个模块有可以帮忙的子任务吗

**Comment by Ayase-252** [comment]
@fimars 小组成员页有兴趣吗？

**Comment by fimars** [comment]
> @fimars 小组成员页有兴趣吗？

好的喵

**Comment by Ayase-252** [comment]
@fimars 设计在一楼的 figma 里有，接口在 private 里。URL 按旧 bgm 的相同页面的 URL 就行

**Comment by Trim21** [comment]
接口在dev-docs里

**Comment by trim21** [comment]
是个问题。server仓库？

Qingyu Deng ***@***.***> 于2022年6月15日周三 23:15写道：

**Comment by trim21** [comment]
…这是GitHub还是Gmail出问题了，这好象是我几个月前的邮件回复
